### ISSUE TITLE
supported ACF fields

### ISSUE THREAD

**Issue by Surgeonito** [wikitribune/fabrica-collaborative-editing#1]
It seems that image fields are not supported.

**Comment by andrewstaffell** [comment]
That’s correct, in the current version only textual Advanced Custom Fields are supported. Other types of fields would require field-specific processing and diff interfaces. We may add these in a future version but are not currently working on them.

If you are able to work on it with a view to submitting a pull request, a good place to start would be line 207 of `inc/base.php`, within the `checkEditConflicts()` function, where we exclude the non-textual field types.
